stages:
  - build
  - test
  - release

variables:
  DOCKER_DRIVER: overlay2
  npm_config_cache: /builds/frontend/open-source/eslint-config/.npm

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

release:
  image: node:8.12-alpine
  stage: release
  before_script:
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
  script:
    - npm publish
  only:
    - master
